sudo: required
language: cpp

os: linux
dist: focal
compiler: gcc

addons:
  apt:
    packages:

      # OpenMPI
      - openmpi-bin
      - libopenmpi-dev

      # fortran
      - gfortran

       # math libraries
      - libblas-dev
      - liblapack-dev

# Handle git submodules
git:
    submodules: true

install:
  - sh scripts/build.sh

script:
  - ./build/boosting --numIterations=3 ./data/servo.data
  - mpirun -np 2 ./build/boosting --numIterations=3 ./data/servo.data
