sudo: required
language: cpp

os: linux

# Ubuntu 20.04 focal
# Ubuntu 18.04 bionic
dist: bionic
compiler: gcc

addons:
  apt:
    packages:

      # OpenMPI
      - openmpi-bin
      - libopenmpi-dev

      # fortran
      - gfortran

       # math libraries
      - libblas-dev
      - liblapack-dev

# Handle git submodules
git:
    submodules: true

install:
  - sh scripts/build.sh
  - sh scripts/build_gurobi.sh
  - cd build; rm -rf *; cmake -DENABLE_GUROBI=false ..

script:
  - ./boosting --numIterations=3 ./data/servo.data
  - mpirun -np 2 /boosting --numIterations=3 ./data/servo.data
