sudo: required
language: cpp

# Ubuntu 18.04 bionic
# Ubuntu 20.04 focal

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          packages:
            # OpenMPI
            - openmpi-bin
            - libopenmpi-dev

            # fortran
            - gfortran

             # math libraries
            - libblas-dev
            - liblapack-dev

    - os: linux
      dist: focal
      compiler: gcc
      addons:
        apt:
          packages:
            # OpenMPI
            - openmpi-bin
            - libopenmpi-dev

            # fortran
            - gfortran

             # math libraries
            - libblas-dev
            - liblapack-dev


# Handle git submodules
git:
    submodules: true

install:
  - sh scripts/build.sh -g gurobi
  - cd build; rm -rf *; cmake -DENABLE_GUROBI=false ..; make; cd ..

script:
  - ./build/boosting --numIterations=3 ./data/servo.data
  # - mpirun -np 2 ./build/boosting --numIterations=3 ./data/servo.data
